CREATE TABLE dbo.Orders (
  OrderId INT IDENTITY(1,1) PRIMARY KEY,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Status NVARCHAR(50) NOT NULL,
  ExpectedShipDateUtc DATETIME2 NOT NULL,
  ActualShipDateUtc DATETIME2 NULL,
  Carrier NVARCHAR(100) NULL,
  DelayReason NVARCHAR(200) NULL
);

CREATE TABLE dbo.PolicyDocuments (
  DocId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL,
  SourceName NVARCHAR(200) NOT NULL,
  UploadedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.PolicyChunks (
  ChunkId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  DocId UNIQUEIDENTIFIER NOT NULL,
  ChunkIndex INT NOT NULL,
  ChunkText NVARCHAR(MAX) NOT NULL,
  Embedding VECTOR(1536) NOT NULL,
  MetadataJson NVARCHAR(MAX) NOT NULL,
  CONSTRAINT FK_PolicyChunks_Documents
    FOREIGN KEY (DocId) REFERENCES dbo.PolicyDocuments(DocId)
);

CREATE TABLE dbo.AuditLog (
  AuditId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  CorrelationId UNIQUEIDENTIFIER NOT NULL,
  OccurredAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ActorUserId NVARCHAR(100) NOT NULL,
  EventType NVARCHAR(60) NOT NULL,
  PayloadJson NVARCHAR(MAX) NOT NULL
);

CREATE TABLE dbo.ApprovalRequest (
  ApprovalId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  CorrelationId UNIQUEIDENTIFIER NOT NULL,
  RequestedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  RequestedByUserId NVARCHAR(100) NOT NULL,
  Status NVARCHAR(20) NOT NULL,
  ToolName NVARCHAR(200) NOT NULL,
  ParamsHash NVARCHAR(128) NOT NULL,
  ParamsJson NVARCHAR(MAX) NOT NULL,
  RiskSummary NVARCHAR(1000) NOT NULL,
  ApprovedAtUtc DATETIME2 NULL,
  ApprovedByUserId NVARCHAR(100) NULL
);

CREATE TABLE dbo.AgentCheckpoint (
  CheckpointId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  CorrelationId UNIQUEIDENTIFIER NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Status NVARCHAR(20) NOT NULL,
  ConversationSummary NVARCHAR(MAX) NOT NULL,
  PendingActionJson NVARCHAR(MAX) NULL,
  LastToolCallId UNIQUEIDENTIFIER NULL
);
